apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-hub
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: game-hub
  template:
    metadata:
      labels:
        app: game-hub
    spec:
      containers:
        - name: game-hub
          image: isankitraj/gamehub:1.0 # Replace with your actual Docker image name
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-hub
spec:
  selector:
    app: game-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
