apiVersion: apps/v1
kind: Deployment
metadata:
  name: playquest
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: playquest
  template:
    metadata:
      labels:
        app: playquest
    spec:
      containers:
        - name: playquest
          image: ankitrajxd/playquest:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: playquest
spec:
  selector:
    app: playquest
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  type: LoadBalancer
